-- ============================================================
-- SOLELY SECURE LINKS MIGRATION
-- Date: 2026-05-30
-- Adds: payment_links table to support guest checkouts and custom invoices
-- ============================================================

CREATE TABLE IF NOT EXISTS public.payment_links (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  vendor_id        UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id       UUID REFERENCES public.products(id) ON DELETE SET NULL,
  custom_title     TEXT,
  custom_price_ksh INTEGER,
  delivery_fee_ksh INTEGER DEFAULT 0,
  is_active        BOOLEAN DEFAULT true,
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW(),
  
  -- Ensure that either a product is linked OR custom details are provided
  CONSTRAINT custom_or_product_check CHECK (
    (product_id IS NOT NULL) OR 
    (custom_title IS NOT NULL AND custom_price_ksh IS NOT NULL)
  )
);

-- Enable RLS
ALTER TABLE public.payment_links ENABLE ROW LEVEL SECURITY;

-- Vendors can view their own links
CREATE POLICY "Vendors can view own payment links"
  ON public.payment_links FOR SELECT
  USING (auth.uid() = vendor_id OR has_role(auth.uid(), 'admin'::app_role));

-- Vendors can insert their own links
CREATE POLICY "Vendors can insert own payment links"
  ON public.payment_links FOR INSERT
  WITH CHECK (auth.uid() = vendor_id AND has_role(auth.uid(), 'vendor'::app_role));

-- Vendors can update their own links (e.g., deactivate)
CREATE POLICY "Vendors can update own payment links"
  ON public.payment_links FOR UPDATE
  USING (auth.uid() = vendor_id AND has_role(auth.uid(), 'vendor'::app_role));

-- Anyone (public guest) can view active payment links to pay
CREATE POLICY "Anyone can view active payment links"
  ON public.payment_links FOR SELECT
  USING (is_active = true);

-- Add updated_at trigger
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.payment_links
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- Add payment_link_id to orders table to track which link generated the order
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS payment_link_id UUID REFERENCES public.payment_links(id) ON DELETE SET NULL,
  ALTER COLUMN customer_id DROP NOT NULL;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_payment_links_vendor_id ON public.payment_links(vendor_id);
CREATE INDEX IF NOT EXISTS idx_orders_payment_link_id ON public.orders(payment_link_id);

COMMENT ON TABLE public.payment_links IS 'Stores secure invoice links generated by vendors for buyers (both custom items and existing products).';
