project_id = "ktoodrjfytteppnpyhvi"

[functions.mpesa-stk-push]
verify_jwt = true

[functions.mpesa-callback]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = true

[functions.intasend-webhook]
verify_jwt = false

[functions.verify-package-pin]
verify_jwt = true

[functions.report-stolen-item]
verify_jwt = true